# Generated by Django 4.1 on 2022-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcode_test", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="file", name="filepath",),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(null=True, upload_to="files/"),
        ),
    ]
