# Generated by Django 4.1 on 2022-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcode_test", "0002_remove_file_filepath_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="filtered_files",
            field=models.FileField(null=True, upload_to="filtered_files/"),
        ),
    ]
