# Generated by Django 4.1 on 2022-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcode_test", "0003_file_filtered_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilteredFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filtered_files",
                    models.FileField(null=True, upload_to="filtered_files/"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="file", name="filtered_files",),
    ]
