# Generated by Django 4.1 on 2022-10-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("super_searcher", "0002_images_name"),
    ]

    operations = [
        migrations.DeleteModel(name="Images",),
    ]
