# Generated by Django 4.1 on 2022-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super_searcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
